name: Build to GCR

on:
  workflow_dispatch:
  push:
    # branches: [main]

env:
  PRODUCT_NAME: "Astro-Analytics"
  PRODUCT_VERSION: ${{ github.run_number}}  # Set your version here

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    permissions:    
      id-token: write
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEMO_GH_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/astro-analytics:latest
            ghcr.io/${{ github.repository_owner }}/astro-analytics:${{ env.PRODUCT_VERSION }}


      - name: Create and Upload SBOM verify SLSA
        uses: scribe-security/action-verify@master
        env: 
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: "ghcr.io/${{ github.repository_owner }}/astro-analytics:${{ env.PRODUCT_VERSION }}"
          bom: true
          provenance: true
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          base-image: Dockerfile
          components: files
          format: attest
          initiative: slsa.l2@v2
          beautify: true

      - name: verify-sp800-190
        uses: scribe-security/action-verify@master
        if: always()
        env: 
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: "ghcr.io/${{ github.repository_owner }}/astro-analytics:${{ env.PRODUCT_VERSION }}"
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          base-image: Dockerfile
          # input: trivy:trivy-report.json # 2DO Scribe CVE rule to initiative willr replace this requriement.
          format: attest
          initiative: sp-800-190@v2
          beautify: true

      - name: verify-ssdf
        if: always()
        uses: scribe-security/action-verify@master
        env: 
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: "ghcr.io/${{ github.repository_owner }}/astro-analytics:${{ env.PRODUCT_VERSION }}"
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          base-image: Dockerfile
          components: files
          format: attest
          initiative: ssdf@v2
          beautify: true
        

