name: Scribe K8S Discover

on:
  # End of pipeline.yml
    workflow_dispatch:
    workflow_run:
      workflows: ["Run Pipeline"]  # Matches the name of the first workflow
      types:
      - completed  # Triggers when the workflow completes (successful or failed)
    pull_request:

jobs:
  deploy-and-discover:
     
    name: Discover and Evaluate K8s
    uses: scribe-public/reusable-workflows/.github/workflows/k8s-demo.yaml@mikey_test
    with:
        scribe_valint_url: "https://api.scribesecurity.com"
        scribe_product_name: "Astro-Analytics"
        scribe_product_version: ${{ vars.VERSION }}
        targets: "scribesecurity/astro-analytics:latest"
        log_level: TRACE
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_HEYMAN_TEAM_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


