name: Discover (agentless) Pipeline

on:
  workflow_dispatch:

jobs: 
  create-gh-evidence:
    name: Discover and Policy - Github
    uses: scribe-public/reusable-workflows/.github/workflows/github-demo.yaml@main
    with:
        scribe_valint_url: "https://api.scribesecurity.com"
        scribe_product_name: "Astro-Analytics-Discovery"
        scribe_product_version: ${{ vars.VERSION }}
        discover_args: "--commit.skip --scope.workflow.past_days 2 --scope.workflow.analyzed_logs"
    
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_HEYMAN_TEAM_TOKEN }}
        GH_TOKEN: ${{ secrets.DEMO_GH_SECRET }}

  deploy-and-create-evidence:
    name: Discover K8s
    uses: scribe-public/reusable-workflows/.github/workflows/k8s-demo.yaml@main
    with:
        scribe_valint_url: "https://api.scribesecurity.com"
        scribe_product_name: "Astro-Analytics-Discovery"
        scribe_product_version: ${{ vars.VERSION }}
        targets: ghcr.io/scribe-public/astro-analytics:latest
        docker-registry: ghcr.io
        sbom: true
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_HEYMAN_TEAM_TOKEN }}
        DOCKERHUB_USERNAME: ${{ github.actor }}
        DOCKERHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        
