name: Run Pipeline

on:
  workflow_dispatch:

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Image
    uses: docker/build-push-action@v2
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: scribesecurity/astro-analytics
      tags: latest
      context: .
      push: false


      
