name: Run Pipeline

on:
  workflow_dispatch:

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    -  name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        tags: scribesecurity/astro-analytics:latest
        context: .
        push: false


      
