jobs:
  policy:
    uses: ./.github/workflows/_policy-core.yml
    with:
      upload:         false
      product_suffix: "-preview"
      image-registry: ghcr.io
      image-name:     astro-analytics-slim
      dockerfile:     Dockerfile_slim
      build-context:  .
    secrets:
      SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
