name: Policy Release Check

on:
  # automatic path – real tag push
  push:
    tags: [ 'v*' ]

  # manual path – mock a tag via “Run workflow”
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name to emulate, e.g. v1.2.4-rc2"
        required: true
        type: string

jobs:
  policy:
    if: ${{ github.event_name == 'push' || github.event.inputs.tag != '' }}
    uses: ./.github/workflows/_policy-core.yml
    with:
      upload:          true                 
      product_suffix:  "-release"
      image-registry:  ghcr.io
      image-name:      astro-analytics-slim
      dockerfile:      Dockerfile_slim
      build-context:   .
      scribe-url:     https://api.staging.scribesecurity.com
    secrets:
      SCRIBE_TOKEN: ${{ secrets.SCRIBE_STAGING_TOKEN }}
    env:
      GITHUB_REF: ${{ github.event_name == 'workflow_dispatch'
                      && format('refs/tags/{0}', github.event.inputs.tag)
                      || github.ref }}
